# Generated by Django 4.1 on 2022-08-22 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dokon', models.CharField(max_length=50)),
                ('ism', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
                ('manzil', models.CharField(max_length=60)),
                ('qarz', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('brend', models.CharField(max_length=50)),
                ('k_narh', models.IntegerField()),
                ('s_narh', models.IntegerField()),
                ('miqdor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ombor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=30)),
                ('nom', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=40)),
                ('manzil', models.CharField(max_length=60)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sana', models.DateTimeField(auto_now_add=True)),
                ('miqdor', models.IntegerField()),
                ('umumiy', models.IntegerField()),
                ('toladi', models.IntegerField()),
                ('nasiya', models.IntegerField()),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='omborapp.client')),
                ('mahsulot', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='omborapp.mahsulot')),
                ('ombor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='omborapp.ombor')),
            ],
        ),
        migrations.AddField(
            model_name='mahsulot',
            name='ombor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omborapp.ombor'),
        ),
        migrations.AddField(
            model_name='client',
            name='ombor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omborapp.ombor'),
        ),
    ]
